name: Update JSON on Push

on:
  push:
    branches:
      - main  # You can change this to the branch you want to trigger the action on

jobs:
  update_json:
    runs-on: ubuntu-latest  # You can change the runner type if needed

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update JSON
        run: |
          # Get the current date in "YYYYMMDD" format
          current_date=$(date -u +"%Y%m%d")

          # Modify the JSON file by updating the "version_test" key
          jq --arg new_date "$current_date" '.version_test = $new_date' Client.json > updated_Client.json

          # Replace the original JSON file with the updated one
          mv updated_Client.json Client.json

          # Commit the changes and push them back to the repository
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add Client.json
          git commit -m "Update client.json"
          git push
